"""sync remaining tables

Revision ID: 918047c9da95
Revises: 0001_initial_schema
Create Date: 2026-03-22 06:05:51.319176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918047c9da95'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'tax',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('bills', 'service_fee',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('bills', 'discount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('bills', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', name='billstatus'),
               nullable=False)
    op.alter_column('bills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredients', 'stock_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('ingredients', 'alert_threshold',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('menu_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('menu_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modifiers', 'extra_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('modifiers', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_items', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PREPARING', 'READY', 'SERVED', name='orderitemstatus'),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               nullable=False)
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reservations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CANCELLED', name='reservationstatus'),
               nullable=False)
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tables', 'status',
               existing_type=postgresql.ENUM('EMPTY', 'OCCUPIED', 'RESERVED', 'CLEANING', name='tablestatus'),
               nullable=False)
    op.alter_column('tables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('variants', 'extra_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variants', 'extra_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tables', 'status',
               existing_type=postgresql.ENUM('EMPTY', 'OCCUPIED', 'RESERVED', 'CLEANING', name='tablestatus'),
               nullable=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reservations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CANCELLED', name='reservationstatus'),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', name='orderstatus'),
               nullable=True)
    op.alter_column('order_items', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PREPARING', 'READY', 'SERVED', name='orderitemstatus'),
               nullable=True)
    op.alter_column('modifiers', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('modifiers', 'extra_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('menu_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('menu_items', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('inventory_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ingredients', 'alert_threshold',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('ingredients', 'stock_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bills', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', name='billstatus'),
               nullable=True)
    op.alter_column('bills', 'discount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('bills', 'service_fee',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('bills', 'tax',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    # ### end Alembic commands ###
