"""remove qr_token

Revision ID: a1ae2ad8a292
Revises: b571287c8884
Create Date: 2026-06-20 16:09:37.119381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ae2ad8a292'
down_revision: Union[str, Sequence[str], None] = 'b571287c8884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tables_qr_token_key'), 'tables', type_='unique')
    op.drop_column('tables', 'qr_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('qr_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('tables_qr_token_key'), 'tables', ['qr_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
